### ISSUE TITLE
Short districts create incorrectly named directories

### ISSUE THREAD

**Issue by madwort** [ingenerator/code-point-simple#2]
A postcode in the current upstream source CSV such as "M1  1AD" produces for me data in `M/1 /1.json` (trailing space). I think this would break your sample code for retrieving data as that would look for the file at `M/1/1.json` (no trailing space)?

**Comment by acoulton** [comment]
@madwort thanks for the bug report, and your interest in the package.

You'll see we've not yet made it to a release on this - we were building it for a project that ultimately didn't need it, and the developer who built it for us has since left the company. 

I've recently discovered http://postcodes.io/ which offers a similarly simple service with a bit more of the data available, and is available as a free and unlimited hosted API or an open source project for self-hosting.

We've not used it yet, but I think we're planning to mark this package as abandoned and recommend people check that out instead.

If you're keen to use code-point-simple I'd be happy to accept a pull request if you can identify where the trailing space is coming from. My first guess was the regex around [here](https://github.com/ingenerator/code-point-simple/blob/master/src/Ingenerator/CodePointSimple/CodePointSimple.php#L104) but I checked that quickly in the console and it does seem to be producing the expected result for `M1 1AD`.

**Comment by madwort** [comment]
Hah, ok, fair enough. Maybe just mark it as abandoned then - I was looking for something simple & PHP based and this came up in a search but as you say there's plenty of other options for doing this, I'll go elsewhere.

**Comment by acoulton** [comment]
Thanks @madwort
